# To execute this docker-compose yml file use `docker-compose -f docker-compose-v3-dynamic-grid.yml up`
# Add the `-d` flag at the end for detached execution
# To stop the execution, hit Ctrl+C, and then `docker-compose -f docker-compose-v3-dynamic-grid.yml down`
version: "3"
services:
  node-docker:
    image: selenium/node-docker:4.10.0
    shm_size: 2gb
    volumes:
      - ./assets:/opt/selenium/assets
      - ./docker-grid-config.toml:/opt/bin/config.toml
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - selenium-hub
    networks:
      - test_network
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_SCREEN_WIDTH=1360
      - SE_SCREEN_HEIGHT=1020
      - TZ=UTC
      - SE_VNC_NO_PASSWORD=1
      - SE_SESSION_REQUEST_TIMEOUT=5400

  selenium-hub:
    image: selenium/hub:4.10.0
    container_name: selenium-hub
    networks:
      - test_network
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

networks:
  test_network:
    attachable: true